[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"

[features]
amd-sev = [ "codicon", "procfs", "reqwest", "serde", "serde_json", "sev", "ureq" ]

[dependencies]
env_logger = "0.9.0"
libc = ">=0.2.39"
log = "0.4.0"
vm-memory = { version = "0.7.0", features = ["backend-mmap"] }
syscall_filter = { path = "../syscall_filter" }
arch = { path = "../arch" }
devices = { path = "../devices" }
kernel = { path = "../kernel" }
utils = { path = "../utils"}
polly = { path = "../polly" }

# Dependencies for amd-sev
codicon = { version = "3.0.0", optional = true }
procfs = { version = "0.10.1", optional = true }
reqwest = { version = "0.9.15", optional = true }
serde = { version = "1.0.125", optional = true }
serde_json = { version = "1.0.64", optional = true }
sev = { version = "0.1.0", features = ["openssl"], optional = true }
ureq = { version = "*", features = ["json"], optional = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
cpuid = { path = "../cpuid" }

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = { version = ">=0.2", features = ["fam-wrappers"] }
kvm-ioctls = ">=0.4"

[target.'cfg(target_os = "macos")'.dependencies]
hvf = { path = "../hvf" }

[dev-dependencies]
vmm-sys-util = ">=0.7.0"
